### PR TITLE
Reactive Mongo Support

### PR DESCRIPTION
**Pull request by codependent**
Related issue: https://github.com/lukas-krecan/ShedLock/issues/248

Since `LockProvider` is blocking I implemented it with temporal locking at subscription time.

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Thanks, I will take a look at it in next few days

**Comment by lukas-krecan** [comment]
I have taken the liberty to cleanup the code a bit https://github.com/lukas-krecan/ShedLock/pull/250/commits

**Comment by codependent** [comment]
@lukas-krecan Thanks for merging the PR :-)

Just one really small detail: I'd say that wrapping the Publisher in a Supplier (`static <T> T execute(Supplier<Publisher<T>> command) {`) is not necessary and something like this would be  fine:

```
            execute(getCollection().findOneAndUpdate(
                and(eq(ID, lockConfiguration.getName()), lte(LOCK_UNTIL, now)),
                update,
                new FindOneAndUpdateOptions().upsert(true)
            ));
...
```

```
    static <T> T execute(Publisher<T> command) {
        SingleLockableSubscriber<T> subscriber = new SingleLockableSubscriber<>();
        command.subscribe(subscriber);
        subscriber.await();
        Throwable error = subscriber.getError();
        if (error != null) {
            if (error instanceof RuntimeException) {
                throw (RuntimeException) error;
            } else {
                throw new LockException("Error when executing Mongo statement", error);
            }
        } else {
            return subscriber.getValue();
        }
    }
```

**Comment by lukas-krecan** [comment]
you ar right, thanks

**Pull request merged**
