### PR TITLE
#2153 Add a ShedLock provider for commercetools

### PR DESCRIPTION
**Pull request by studix**
ShedLock provider that uses commercetools custom objects to persist lock information. Custom objects are a key/value document store that is part of the API extensibility provided by the platform.

Could not inherit the integration test from AbstractLockProviderIntegrationTest as there is no test container for commercetools. Used a http mock server instead.

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Hi, thanks. But I am afraid I can't merge it without the integration tests as I will not be able to support it. The integration tests give me confidence that the lock provider works as expected, mocked tests do not help much in this regard. We either have to somehow figure-out how to make the tests work, or you can release your Lock Provider as a standalone project and I will hapilly link it from the documentation.

**Comment by studix** [comment]
I found a docker image that mocks the whole commercetools server. With this I could pass the integration tests.

**Comment by studix** [comment]
Looks like the test fuzzTestShouldPass is flaky. What is this test doing?

**Comment by lukas-krecan** [comment]
It's the most interesting test. It's executing [FuzzTester](https://github.com/lukas-krecan/ShedLock/blob/master/shedlock-test-support/src/main/java/net/javacrumbs/shedlock/test/support/FuzzTester.java) which is incrementing a counter from multiple threads and checkig if the resulting number has the expected value. If the locking does not work, this test usually fails. It's unfortunately hard to tell why the test failed.

**Comment by studix** [comment]
I got the FuzzTester green with the mocked and the real commercetools API. It's stable on my machine. But it still fails on the pipeline.

I'm giving up and I'm closing the pull request. You can also close #2153 if you want.

**Comment by lukas-krecan** [comment]
Hi, I looked into the code and there may be a conflict on Insert. Imagine all the threads are executed in parallel. All threds call find [here](https://github.com/BisonSchweizAG/ShedLock/blob/feature/commercetoolsLockProvider/providers/commercetools/shedlock-provider-commercetools/src/main/java/net/javacrumbs/shedlock/provider/commercetools/CommercetoolsStorageAccessor.java#L29), they got null as there is no record and then the call to `createOrUpdateLockValue` succeed as no `version` is sent. I am not familiar with the API, so I am not sure it's the case. What do you think?

**Comment by studix** [comment]
Calling find would actually not be necessary as the api has a createOrUpdate semantic. It is guaranteed by commercetools that there will be no duplicate custom obects with the same key (lock name). I‘m catching this in the insert method and return empty

**Pull request closed without merging**
