### PR TITLE
#1779 Ability to rethrow unexpected exception in JdbcTemplateStorageAccessor

### PR DESCRIPTION
**Pull request by lukas-krecan**

### CODE REVIEW

**Comment by VenkateshJhipster** [comment]
@lukas-krecan  Can pls confirm if this fix is available to download from Maven repository?

**Comment by lukas-krecan** [comment]
Hi, first of all it's not a fix. It will allow you to do retry if you wrap the LockProvider by your own wrapper similar to [this](https://github.com/lukas-krecan/ShedLock?tab=readme-ov-file#customization). I have not merged it yet as I am waiting for your confirmation that it's something you want to do. I do not want to merge something that's not going to be used.

To reiterate. If we merge it, you will have to wrap LockProvider, catch the exception and retry. Is it something you want to try or not?

**Comment by ivankhoosty** [comment]
Hi @lukas-krecan , this is a very useful change, I was just about to raise a PR and then noticed you already have this :)

we hit this during DB failover, ERROR: cannot execute UPDATE in a read-only transaction; nested exception is org.postgresql.util.PSQLException: ERROR: cannot execute UPDATE in a read-only transaction.  
Basically, DB goes into read-only mode, and all insert/update queries fail with UncategorizedSQLException.

we are using shedlock for scheduling, but also as standalone distribute lock provider. while returning empty lock is not catastrophic for scheduling (a run is missed, but presumably the next one will be ok), it's pretty bad for locking, as it basically means the lock cannot be obtained and we skip certain actions.

my question is why have you only singled out UncategorizedSQLException and not the whole catch block (regardless of exceptions listed, they are basically classed by shedlock as "Unexpected exceptionS", maybe the change would be even more useful if LockConfiguration had throwUnexpectedExceptionS (plural), and then all exceptions in that catch block would qualify .

**Comment by lukas-krecan** [comment]
Cool, I will merge it then

**Comment by lukas-krecan** [comment]
@ ivankhoosty Released in 5.13.0

**Comment by lukas-krecan** [comment]
@ivankhoosty Released in 5.13.0

**Comment by ivankhoosty** [comment]
Thanks for a quick turnaround on this !

**Pull request merged**
