### PR TITLE
spring-data-redis:2.0.6.RELEASE, lettuce-core:5.0.3.RELEASE

### PR DESCRIPTION
**Pull request by nkonev**
Hi, it doesn't works with Spring Boot 2 Bom' provided spring-data-redis
so I updated libraries for fix it

### CODE REVIEW

**Comment by nkonev** [comment]
Ping @lukas-krecan

**Comment by lukas-krecan** [comment]
Hi, sorry I am on vacation. I will have to think about it since updating the dependency is most likely going to break backward compatibility. I assume that you just can not change the dependency in your module, is that correct?

**Comment by nkonev** [comment]
Yes, I cannot change this dependencies back because I use Spring Boot's BOM.

**Comment by lukas-krecan** [comment]
In such case, you can explicitly specify the dependency in your pom. I will make it more BOM compatible in few weeks.

**Comment by lukas-krecan** [comment]
Hi, I have a project with spring-boot BOM and spring-data-redis (https://github.com/lukas-krecan/shedlock-example/blob/spring-boot/pom.xml) and the version of spring-data-redis is taken from BOM and not from ShedLock so it should work in your case as expected. Is there anything I am missing? 

```
mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building shedlock-example 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ shedlock-example ---
[INFO] net.javacrumbs.shedlock-example:shedlock-example:jar:1.0-SNAPSHOT
[INFO] +- net.javacrumbs.shedlock:shedlock-spring:jar:0.18.2:compile
[INFO] |  +- net.javacrumbs.shedlock:shedlock-core:jar:0.18.2:compile
[INFO] |  +- org.springframework:spring-context:jar:5.0.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.0.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:5.0.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-core:jar:5.0.5.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.0.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.0.5.RELEASE:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] \- net.javacrumbs.shedlock:shedlock-provider-redis-spring:jar:0.18.2:compile
[INFO]    \- org.springframework.data:spring-data-redis:jar:2.0.6.RELEASE:compile
[INFO]       +- org.springframework.data:spring-data-keyvalue:jar:2.0.6.RELEASE:compile
[INFO]       |  \- org.springframework.data:spring-data-commons:jar:2.0.6.RELEASE:compile
[INFO]       +- org.springframework:spring-tx:jar:5.0.5.RELEASE:compile
[INFO]       +- org.springframework:spring-oxm:jar:5.0.5.RELEASE:compile
[INFO]       \- org.springframework:spring-context-support:jar:5.0.5.RELEASE:compile
```

**Comment by nkonev** [comment]
@lukas-krecan 
Sorry for long response.

Anyway, I had error during unlocking.

```
2018-06-03 23:10:00.061  INFO 17100 --- [TaskScheduler-1] imagesCleanTask                          : Cleared 0 post content images(created before 1 day ago); 0 post title images; 0 user avatar images
2018-06-03 23:10:00.068 ERROR 17100 --- [TaskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[BLorg/springframework/data/redis/core/types/Expiration;Lorg/springframework/data/redis/connection/RedisStringCommands$SetOption;)V
	at net.javacrumbs.shedlock.provider.redis.spring.RedisLockProvider$RedisLock.unlock(RedisLockProvider.java:115) ~[shedlock-provider-redis-spring-0.18.2.jar:na]
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:44) ~[shedlock-core-0.18.2.jar:na]
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51) ~[shedlock-core-0.18.2.jar:na]
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35) ~[shedlock-core-0.18.2.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) [na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
```
with original version shedlock. project [branch](https://github.com/nkonev/blog/tree/redis).

I tested with my patched(I install it to maven local), error is gone.

**Comment by lukas-krecan** [comment]
Hi, thanks. Apparently they have changed method signature of the set method so it has to be recompiled with the new version. Will update the libraries and release new version.

**Comment by lukas-krecan** [comment]
Released as 1.0.0

**Comment by nkonev** [comment]
@lukas-krecan Yes, it works, thanks

**Pull request closed without merging**
