### PR TITLE
Better insert statement for MySQL

### PR DESCRIPTION
**Pull request by onlinemd**
@lukas-krecan Syntax error has been corrected, can you please check it now

Mysql update on conflict syntax works as below

INSERT INTO shedlock(name,lock_until,locked_at,locked_by) 
VALUES('shedlock', '2022-09-05 11:58:52.059', '2022-09-05 12:58:52.059','admin') 
ON DUPLICATE KEY UPDATE lock_until = '2022-10-31 11:58:52.059', locked_at= '2022-10-31 12:58:52.059', locked_by='Iadmin';

MySql reference link - 

https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

### CODE REVIEW

**Comment by lukas-krecan** [comment]
Thanks, does the test I mentioned in the previous comment pass?

**Comment by onlinemd** [comment]
@lukas-krecan sorry for the trouble, I had issues running the set up in my local. Can you please validate or provide me some brief to set up in local and execute

**Comment by lukas-krecan** [comment]
Hi, I think you just need docker and then you can run the test from your IDE. If it does not work, please let me know why

**Comment by onlinemd** [comment]
> Hi, I think you just need docker and then you can run the test from your IDE. If it does not work, please let me know why

@lukas-krecan I can't install the docker in my local due to admin restrictions.

**Comment by onlinemd** [comment]
> > Hi, I think you just need docker and then you can run the test from your IDE. If it does not work, please let me know why
> 
> @lukas-krecan I can't install the docker in my local due to admin restrictions.

@lukas-krecan Can you please check at your end for once now?

**Comment by lukas-krecan** [comment]
As I have written in one of my previous comments, the code can't work without specifying the WHERE clause as in the Postgres [version](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/PostgresSqlServerTimeStatementsSource.java#L40)

**Comment by onlinemd** [comment]
> INSERT INTO shedlock(name,lock_until,locked_at,locked_by) VALUES('shedlock', '2022-09-05 11:58:52.059', '2022-09-05 12:58:52.059','admin') ON DUPLICATE KEY UPDATE lock_until = '2022-10-31 11:58:52.059', locked_at= '2022-10-31 12:58:52.059', locked_by='Iadmin';
> 
> MySql reference link -
> 
> https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html



> As I have written in one of my previous comments, the code can't work without specifying the WHERE clause as in the Postgres [version](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/main/java/net/javacrumbs/shedlock/provider/jdbctemplate/PostgresSqlServerTimeStatementsSource.java#L40)



@lukas-krecan for Mysql it works in a different way, on update clause will auto apply the unique/primary key as a where clause. I had tested the below query in my local and it's working. Please do find the attached link of mysql documentation for the same.

INSERT INTO shedlock(name,lock_until,locked_at,locked_by)
VALUES('shedlock', '2022-09-05 11:58:52.059', '2022-09-05 12:58:52.059','admin')
ON DUPLICATE KEY UPDATE lock_until = '2022-10-31 11:58:52.059', locked_at= '2022-10-31 12:58:52.059', locked_by='Iadmin';

MySql reference link -

https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

**Comment by lukas-krecan** [comment]
Yes, the update works. But the logic should work this way:
1. If the record does not exist, create it (the insert part)
2. If the record does exist update it **only if `lock_until  < now`**
3. If `lock_until > now` do not do anything as somebody else is holding the lock

Your code always updates the lock which is not desired.

**Comment by onlinemd** [comment]
@lukas-krecan did you get any chance to look at the latest changes?

**Comment by lukas-krecan** [comment]
Hi, the statement itself works (cool trick by the way). The issue is that ShedLock needs to detect if current process holds the lock. Currently the logic is: if the insert statement inserted/updated a row, we held the lock. If not, it was held by somebody else.

Your insert statement always updates a row.  Even if lock_until > now, the update happens, it just writes the same values. So  the JDBC driver reports it as a row update and ShedLock interpets it as if we held the lock.

You can see the test results [here](https://github.com/lukas-krecan/ShedLock/actions/runs/3015107428) (once they finish)

**Comment by onlinemd** [comment]
@lukas-krecan Can you please check the below screenshots? 

**Sample example:**

lock is held at 1PM and until 2PM by admin. Now when I ran the modified insert/update query at 01:31 PM, no records are updated as lock until > now(). As 0 records are updated, do we considered this as a lock acquired by the new instance (as per my query admin2)?

I'm eagerly looking for this issue to be solved, If i'm not going in a right direction can you provide us a better alternative. Thanks

**Current Local Time**
image

**Current row information**
image

INSERT/UPDATE query result -> No records are updated when lock_until > now()
image

**Comment by lukas-krecan** [comment]
Hi, it's not about state in the database, it's about state in the JVM. JDBC driver reports 1 updated row. I am afraid, this PR will not be possible to finish without you being able to run the tests.

Can you please replace MySqlConfig [here](https://github.com/lukas-krecan/ShedLock/blob/master/providers/jdbc/shedlock-provider-jdbc-template/src/test/java/net/javacrumbs/shedlock/provider/jdbctemplate/MySqlJdbcTemplateLockProviderIntegrationTest.java#L23) by your implementation of DbConfig which can connect to your MySQL?

**Comment by TomBeckett** [comment]
@onlinemd I've ran the tests locally and they do indeed fail for me. This is the SQL generated:

```sql
INSERT INTO
  shedlock(name, lock_until, locked_at, locked_by)
VALUES(
    :name,
    TIMESTAMPADD(
      MICROSECOND,
      :lockAtMostForMicros,
      UTC_TIMESTAMP(3)
    ),
    UTC_TIMESTAMP(3),
    :lockedBy
  ) ON DUPLICATE KEY
UPDATE
  lock_until = IF(
    lock_until <= UTC_TIMESTAMP(3),
    VALUES(lock_until),
      lock_until
  ),
  locked_at = IF(
    lock_until <= UTC_TIMESTAMP(3),
    VALUES(locked_at),
      locked_at
  ),
  locked_by = IF(
    lock_until <= UTC_TIMESTAMP(3),
    VALUES(locked_by),
      locked_by
  )
```

Does this look correct to you?

**Comment by lukas-krecan** [comment]
> Hi, the statement itself works. The issue is that ShedLock needs to detect if current process holds the lock. Currently the logic is: if the insert statement inserted/updated a row, we held the lock. If not, it was held by somebody else.
> 
> Your insert statement always updates a row. Even if lock_until > now, the update happens, it just writes the same values. So the JDBC driver reports it as a row update and ShedLock interpets it as if we held the lock.

If you debug one of the failing tests, you will see that the JDBC driver reports 1 inserted row. I am afraid, that what you are trying to do is impossible in MySQL.

**Comment by lukas-krecan** [comment]
I will merge [this](https://github.com/lukas-krecan/ShedLock/pull/1273), which should fix the issue

**Pull request closed without merging**
