### PR TITLE
RedisFactoryLockProvider impl

### PR DESCRIPTION
**Pull request by siposr**
#47 for this issue.
For this implementation you need SpringBoot.

Configuration is pretty same as the Jedis version but it uses RedisConnectionFactory instead of JedisPool.

### CODE REVIEW

**Comment by clamey** [comment]
Any chance we could get the main REAME updated to include an example of how to set this up?

**Comment by siposr** [comment]
#### Redis (using RedisConnectionFactory)
Import 
```xml
<dependency>
    <groupId>net.javacrumbs.shedlock</groupId>
    <artifactId>shedlock-provider-redis-connectionfactory</artifactId>
    <version>0.17.1</version>
</dependency>
```

and configure

```java
@Bean
public LockProvider lockProvider(RedisConnectionFactory redisConnectionFactory) {
	return new RedisFactoryLockProvider(redisConnectionFactory);
}
```

**Comment by siposr** [comment]
I dunno what's go wrong with my test, if I run in IDE as JUnit it works. Any idea?

**Comment by lukas-krecan** [comment]
Thanks, I will look at it in next few days.

**Comment by marcioviegas** [comment]
Any chance we get this check failed fixed?

**Comment by lukas-krecan** [comment]
Sorry, I do not understand?

**Comment by marcioviegas** [comment]
Why could I not find that code on master?

**Comment by lukas-krecan** [comment]
It's here https://github.com/lukas-krecan/ShedLock/tree/master/shedlock-provider-redis-spring I have renamed the module. I am still not sure about the name, that's why it's not released yet.

**Comment by marcioviegas** [comment]
Ahhh, ok! I just copied the Provider to my code and I will wait for the release. 
Thanks @lukas-krecan

**Comment by clamey** [comment]
Maybe we change the Jedis one to shedlock-provider-redis-jedis to keep these two consistent like the shedlock-provider-jdbc-* ones?

**Comment by lukas-krecan** [comment]
Yes, but it would require to do something like this https://github.com/lukas-krecan/ShedLock/pull/51 in order to keep it backward-compatible  But maybe better now then later.

**Comment by lukas-krecan** [comment]
Released as 0.18.0

**Comment by siposr** [comment]
You should update the Wiki as well.
Thank you guys for my first contribution. :)

**Pull request merged**
