### PR TITLE
Shedlock to support Couchbase

### PR DESCRIPTION
**Pull request by MoranVaisberg**
This pull request contains CouchbaseLockProvider and CouchbaseLockProviderIntegrationTest files to support Shedlock with Couchbase database.

### CODE REVIEW

**Comment by MoranVaisberg** [comment]
.

**Comment by lukas-krecan** [comment]
Cool thanks a lot. It needs some cleanup but overall it looks good.

**Comment by lukas-krecan** [comment]
If you want I can take it from here. But if you prefer to finish it yourself, just let me know, I can provide some feedback how to make the PR better. There is no rush.

**Comment by MoranVaisberg** [comment]
I saw that it is possible to take jar from
https://github.com/couchbase/CouchbaseMock
And then make tests work.
If you can proceed from here, it would be great. Not sure how much available time will have.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Lukáš Křečan <notifications@github.com> Date: 9/21/18  21:30  (GMT+02:00) To: lukas-krecan/ShedLock <ShedLock@noreply.github.com> Cc: MoranVaisberg <moranr76@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [lukas-krecan/ShedLock] Shedlock to support Couchbase (#88) 
If you want I can take it from here. But if you prefer to finish it yourself, just let me know, I can provide some feedback how to make the PR better. There is no rush.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lukas-krecan/ShedLock","title":"lukas-krecan/ShedLock","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lukas-krecan/ShedLock"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lukas-krecan in #88: If you want I can take it from here. But if you prefer to finish it yourself, just let me know, I can provide some feedback how to make the PR better. There is no rush."}],"action":{"name":"View Pull Request","url":"https://github.com/lukas-krecan/ShedLock/pull/88#issuecomment-423631223"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lukas-krecan/ShedLock/pull/88#issuecomment-423631223",
"url": "https://github.com/lukas-krecan/ShedLock/pull/88#issuecomment-423631223",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [lukas-krecan/ShedLock] Shedlock to support Couchbase (#88)",
"sections": [
{
"text": "",
"activityTitle": "**Lukáš Křečan**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lukas-krecan",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lukas-krecan/ShedLock\",\n\"issueId\": 88,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"lukas-krecan/ShedLock\",\n\"pullRequestId\": 88\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lukas-krecan/ShedLock/pull/88#issuecomment-423631223"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 382793961\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by lukas-krecan** [comment]
Thanks, I have been looking at executing tests against real CouchDB as it's the only test that would tell us that it really works. I tried this https://blog.couchbase.com/testing-spring-data-couchbase-applications-with-testcontainers/ but still keep failing.

**Comment by MoranVaisberg** [comment]
When I run tests against real db they pass. 
I created a mock bucket (see the latest upload), and all tests, except FuzzTester, run successfully.
The reason is that CAS algorithm is missing in mock, what fails that test.
I will work on that, once have it, will push it to the repository.

**Comment by lukas-krecan-lt** [comment]
Hi, thanks again, but I do not think you should invest more into the Mock tests. In our case they really are not that useful.

**Comment by lukas-krecan** [comment]
Hi, I made some [changes](https://github.com/lukas-krecan/ShedLock/pull/90/commits/0790fc656c437922aaa5bd3a9e77b4853f479b9a), can you please check that it's ok and if so, I will merge it and release it. Thanks

**Comment by lukas-krecan** [comment]
Merged as part of #90

**Pull request closed without merging**
