### PR TITLE
enable advanced consul-provider configuration

### PR DESCRIPTION
**Pull request by DrWifey**
Ready.
I don't know did I fulfill the code-style you follow, but it seems working)

### CODE REVIEW

**Comment by DrWifey** [comment]
Ready.
I don't know did I fulfill the code-style you follow, but it seems working)

**Comment by lukas-krecan** [comment]
Looks good, thanks. Will release it later this week.

**Comment by lukas-krecan** [comment]
I guess that setting token in setKVValue at al is still missing? And I do not get the DEFAULT_CONSUL_LOCK_POSTFIX, it's backward incompatible change, I would prefer to put there an empty string by default. Is that a problem?

**Comment by lukas-krecan** [comment]
This should fix it https://github.com/lukas-krecan/ShedLock/pull/361

**Comment by DrWifey** [comment]
How is that possible? I didn't modify the default `DEFAULT_CONSUL_LOCK_POSTFIX` value...
https://github.com/DrWifey/ShedLock/blob/shedlock-parent-4.18.0/providers/consul/shedlock-provider-consul/src/main/java/net/javacrumbs/shedlock/provider/consul/ConsulLockProvider.java

**Comment by lukas-krecan** [comment]
My bad, about the default value sorry. I already have PR for the token. Thanks again.

**Comment by lukas-krecan** [comment]
Released as 4.18.0

**Pull request merged**
